"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.MESSAGE_DELETE_RATELIMIT_CHECK_OLDER = exports.MESSAGE_DELETE_RATELIMIT_CHECK = exports.SPOILER_ATTACHMENT_PREFIX = exports.RATELIMIT_BUCKET_MAJOR_PARAMS = exports.RestEvents = exports.RatelimitPrecisionTypes = exports.RatelimitHeaders = exports.DiscordHeaders = exports.DiscordAbortCodes = exports.ActivityActionTypes = exports.AuthTypes = exports.ApiVersion = exports.Package = exports.HTTPMethods = void 0;
var constants_1 = require("detritus-rest/lib/constants");
Object.defineProperty(exports, "HTTPMethods", { enumerable: true, get: function () { return constants_1.HTTPMethods; } });
exports.Package = Object.freeze({
    URL: 'https://github.com/detritusjs/client-rest',
    VERSION: '0.10.5',
});
exports.ApiVersion = 9;
var AuthTypes;
(function (AuthTypes) {
    AuthTypes["BEARER"] = "BEARER";
    AuthTypes["BOT"] = "BOT";
    AuthTypes["USER"] = "USER";
})(AuthTypes = exports.AuthTypes || (exports.AuthTypes = {}));
var ActivityActionTypes;
(function (ActivityActionTypes) {
    ActivityActionTypes[ActivityActionTypes["JOIN"] = 1] = "JOIN";
    ActivityActionTypes[ActivityActionTypes["SPECTATE"] = 2] = "SPECTATE";
    ActivityActionTypes[ActivityActionTypes["LISTEN"] = 3] = "LISTEN";
    ActivityActionTypes[ActivityActionTypes["WATCH"] = 4] = "WATCH";
    ActivityActionTypes[ActivityActionTypes["JOIN_REQUEST"] = 5] = "JOIN_REQUEST";
})(ActivityActionTypes = exports.ActivityActionTypes || (exports.ActivityActionTypes = {}));
var DiscordAbortCodes;
(function (DiscordAbortCodes) {
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_ACCOUNT"] = 10001] = "UNKNOWN_ACCOUNT";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_APPLICATION"] = 10002] = "UNKNOWN_APPLICATION";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_CHANNEL"] = 10003] = "UNKNOWN_CHANNEL";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_GUILD"] = 10004] = "UNKNOWN_GUILD";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_INTEGRATION"] = 10005] = "UNKNOWN_INTEGRATION";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_INVITE"] = 10006] = "UNKNOWN_INVITE";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_MEMBER"] = 10007] = "UNKNOWN_MEMBER";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_MESSAGE"] = 10008] = "UNKNOWN_MESSAGE";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_OVERWRITE"] = 10009] = "UNKNOWN_OVERWRITE";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_PLATFORM"] = 10010] = "UNKNOWN_PLATFORM";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_ROLE"] = 10011] = "UNKNOWN_ROLE";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_TOKEN"] = 10012] = "UNKNOWN_TOKEN";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_USER"] = 10013] = "UNKNOWN_USER";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_EMOJI"] = 10014] = "UNKNOWN_EMOJI";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_WEBHOOK"] = 10015] = "UNKNOWN_WEBHOOK";
    DiscordAbortCodes[DiscordAbortCodes["UNKNOWN_GIFT_CODE"] = 10038] = "UNKNOWN_GIFT_CODE";
    DiscordAbortCodes[DiscordAbortCodes["BOT_DISALLOWED"] = 20001] = "BOT_DISALLOWED";
    DiscordAbortCodes[DiscordAbortCodes["BOT_REQUIRED"] = 20002] = "BOT_REQUIRED";
    DiscordAbortCodes[DiscordAbortCodes["RPC_PROXY_DISALLOWED"] = 20003] = "RPC_PROXY_DISALLOWED";
    DiscordAbortCodes[DiscordAbortCodes["EXPLICIT_CONTENT"] = 20009] = "EXPLICIT_CONTENT";
    DiscordAbortCodes[DiscordAbortCodes["ACCOUNT_SCHEDULED_FOR_DELETION"] = 20011] = "ACCOUNT_SCHEDULED_FOR_DELETION";
    DiscordAbortCodes[DiscordAbortCodes["USER_NOT_AUTHORIZED_FOR_APPLICATION"] = 20012] = "USER_NOT_AUTHORIZED_FOR_APPLICATION";
    DiscordAbortCodes[DiscordAbortCodes["ACCOUNT_DISABLED"] = 20013] = "ACCOUNT_DISABLED";
    DiscordAbortCodes[DiscordAbortCodes["SLOWMODE_RATE_LIMITED"] = 20016] = "SLOWMODE_RATE_LIMITED";
    DiscordAbortCodes[DiscordAbortCodes["CHANNEL_FOLLOWING_EDIT_RATE_LIMITED"] = 20017] = "CHANNEL_FOLLOWING_EDIT_RATE_LIMITED";
    DiscordAbortCodes[DiscordAbortCodes["UNDER_MINIMUM_AGE"] = 20024] = "UNDER_MINIMUM_AGE";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_USER_GUILDS"] = 30001] = "TOO_MANY_USER_GUILDS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_BOT_GUILDS"] = 30001] = "TOO_MANY_BOT_GUILDS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_FRIENDS"] = 30002] = "TOO_MANY_FRIENDS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_PINS_IN_CHANNEL"] = 30003] = "TOO_MANY_PINS_IN_CHANNEL";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_RECIPIENTS"] = 30004] = "TOO_MANY_RECIPIENTS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_GUILD_ROLES"] = 30005] = "TOO_MANY_GUILD_ROLES";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_USING_USERNAME"] = 30006] = "TOO_MANY_USING_USERNAME";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_WEBHOOKS"] = 30007] = "TOO_MANY_WEBHOOKS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_EMOJI"] = 30008] = "TOO_MANY_EMOJI";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_REACTIONS"] = 30010] = "TOO_MANY_REACTIONS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_GUILD_CHANNELS"] = 30013] = "TOO_MANY_GUILD_CHANNELS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_ATTACHMENTS"] = 30015] = "TOO_MANY_ATTACHMENTS";
    DiscordAbortCodes[DiscordAbortCodes["TOO_MANY_ANIMATED_EMOJI"] = 30018] = "TOO_MANY_ANIMATED_EMOJI";
    DiscordAbortCodes[DiscordAbortCodes["NOT_ENOUGH_GUILD_MEMBERS"] = 30029] = "NOT_ENOUGH_GUILD_MEMBERS";
    DiscordAbortCodes[DiscordAbortCodes["UNAUTHORIZED"] = 40001] = "UNAUTHORIZED";
    DiscordAbortCodes[DiscordAbortCodes["EMAIL_VERIFICATION_REQUIRED"] = 40002] = "EMAIL_VERIFICATION_REQUIRED";
    DiscordAbortCodes[DiscordAbortCodes["RATE_LIMIT_DM_OPEN"] = 40003] = "RATE_LIMIT_DM_OPEN";
    DiscordAbortCodes[DiscordAbortCodes["SEND_MESSAGE_TEMPORARILY_DISABLED"] = 40004] = "SEND_MESSAGE_TEMPORARILY_DISABLED";
    DiscordAbortCodes[DiscordAbortCodes["USER_BANNED"] = 40007] = "USER_BANNED";
    DiscordAbortCodes[DiscordAbortCodes["CONNECTION_REVOKED"] = 40012] = "CONNECTION_REVOKED";
    DiscordAbortCodes[DiscordAbortCodes["DELETE_ACCOUNT_TRANSFER_TEAM_OWNERSHIP"] = 40028] = "DELETE_ACCOUNT_TRANSFER_TEAM_OWNERSHIP";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_ACCESS"] = 50001] = "INVALID_ACCESS";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_ACCOUNT_TYPE"] = 50002] = "INVALID_ACCOUNT_TYPE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_ACTION_DM"] = 50003] = "INVALID_ACTION_DM";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_EMBED_DISABLED"] = 50004] = "INVALID_EMBED_DISABLED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MESSAGE_AUTHOR"] = 50005] = "INVALID_MESSAGE_AUTHOR";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MESSAGE_EMPTY"] = 50006] = "INVALID_MESSAGE_EMPTY";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MESSAGE_SEND_USER"] = 50007] = "INVALID_MESSAGE_SEND_USER";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MESSAGE_SEND_NON_TEXT"] = 50008] = "INVALID_MESSAGE_SEND_NON_TEXT";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MESSAGE_VERIFICATION_LEVEL"] = 50009] = "INVALID_MESSAGE_VERIFICATION_LEVEL";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_OAUTH_APP_BOT"] = 50010] = "INVALID_OAUTH_APP_BOT";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_OAUTH_APP_LIMIT"] = 50011] = "INVALID_OAUTH_APP_LIMIT";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_OAUTH_STATE"] = 50012] = "INVALID_OAUTH_STATE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_PERMISSIONS"] = 50013] = "INVALID_PERMISSIONS";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_TOKEN"] = 50014] = "INVALID_TOKEN";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_NOTE"] = 50015] = "INVALID_NOTE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_BULK_DELETE_COUNT"] = 50016] = "INVALID_BULK_DELETE_COUNT";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_MFA_LEVEL"] = 50017] = "INVALID_MFA_LEVEL";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_PASSWORD"] = 50018] = "INVALID_PASSWORD";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_PIN_MESSAGE_CHANNEL"] = 50019] = "INVALID_PIN_MESSAGE_CHANNEL";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_INVITE_CODE"] = 50020] = "INVALID_INVITE_CODE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_SYSTEM_MESSAGE_ACTION"] = 50021] = "INVALID_SYSTEM_MESSAGE_ACTION";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_PHONE_NUMBER"] = 50022] = "INVALID_PHONE_NUMBER";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_CLIENT_ID"] = 50023] = "INVALID_CLIENT_ID";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_CHANNEL_TYPE"] = 50024] = "INVALID_CHANNEL_TYPE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_OAUTH2_ACCESS_TOKEN"] = 50025] = "INVALID_OAUTH2_ACCESS_TOKEN";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_OAUTH2_MISSING_SCOPE"] = 50026] = "INVALID_OAUTH2_MISSING_SCOPE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_WEBHOOK_TOKEN"] = 50027] = "INVALID_WEBHOOK_TOKEN";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_BULK_DELETE"] = 50034] = "INVALID_BULK_DELETE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_FORM_BODY"] = 50035] = "INVALID_FORM_BODY";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_INVITE_ACCEPTED"] = 50036] = "INVALID_INVITE_ACCEPTED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_API_VERSION"] = 50041] = "INVALID_API_VERSION";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_FILE_SIZE"] = 50045] = "INVALID_FILE_SIZE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_FILE"] = 50046] = "INVALID_FILE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_REDEMPTION_EXHAUSTED"] = 50050] = "INVALID_GIFT_REDEMPTION_EXHAUSTED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_REDEMPTION_OWNED"] = 50051] = "INVALID_GIFT_REDEMPTION_OWNED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_SELF_REDEMPTION"] = 50054] = "INVALID_GIFT_SELF_REDEMPTION";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_REDEMPTION_SUBSCRIPTION_MANAGED"] = 100021] = "INVALID_GIFT_REDEMPTION_SUBSCRIPTION_MANAGED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_REDEMPTION_SUBSCRIPTION_INCOMPATIBLE"] = 100023] = "INVALID_GIFT_REDEMPTION_SUBSCRIPTION_INCOMPATIBLE";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_GIFT_REDEMPTION_INVOICE_OPEN"] = 100024] = "INVALID_GIFT_REDEMPTION_INVOICE_OPEN";
    DiscordAbortCodes[DiscordAbortCodes["MFA_ENABLED"] = 60001] = "MFA_ENABLED";
    DiscordAbortCodes[DiscordAbortCodes["MFA_DISABLED"] = 60002] = "MFA_DISABLED";
    DiscordAbortCodes[DiscordAbortCodes["MFA_REQUIRED"] = 60003] = "MFA_REQUIRED";
    DiscordAbortCodes[DiscordAbortCodes["MFA_UNVERIFIED"] = 60004] = "MFA_UNVERIFIED";
    DiscordAbortCodes[DiscordAbortCodes["MFA_INVALID_SECRET"] = 60005] = "MFA_INVALID_SECRET";
    DiscordAbortCodes[DiscordAbortCodes["MFA_INVALID_TICKET"] = 60006] = "MFA_INVALID_TICKET";
    DiscordAbortCodes[DiscordAbortCodes["MFA_INVALID_CODE"] = 60008] = "MFA_INVALID_CODE";
    DiscordAbortCodes[DiscordAbortCodes["MFA_INVALID_SESSION"] = 60009] = "MFA_INVALID_SESSION";
    DiscordAbortCodes[DiscordAbortCodes["PHONE_NUMBER_UNABLE_TO_SEND"] = 70003] = "PHONE_NUMBER_UNABLE_TO_SEND";
    DiscordAbortCodes[DiscordAbortCodes["PHONE_VERIFICATION_REQUIRED"] = 70007] = "PHONE_VERIFICATION_REQUIRED";
    DiscordAbortCodes[DiscordAbortCodes["RELATIONSHIP_INCOMING_DISABLED"] = 80000] = "RELATIONSHIP_INCOMING_DISABLED";
    DiscordAbortCodes[DiscordAbortCodes["RELATIONSHIP_INCOMING_BLOCKED"] = 80001] = "RELATIONSHIP_INCOMING_BLOCKED";
    DiscordAbortCodes[DiscordAbortCodes["RELATIONSHIP_INVALUD_USER_BOT"] = 80002] = "RELATIONSHIP_INVALUD_USER_BOT";
    DiscordAbortCodes[DiscordAbortCodes["RELATIONSHIP_INVALID_SELF"] = 80003] = "RELATIONSHIP_INVALID_SELF";
    DiscordAbortCodes[DiscordAbortCodes["RELATIONSHIP_INVALID_DISCORD_TAG"] = 80004] = "RELATIONSHIP_INVALID_DISCORD_TAG";
    DiscordAbortCodes[DiscordAbortCodes["REACTION_BLOCKED"] = 90001] = "REACTION_BLOCKED";
    DiscordAbortCodes[DiscordAbortCodes["LISTING_ALREADY_JOINED"] = 120000] = "LISTING_ALREADY_JOINED";
    DiscordAbortCodes[DiscordAbortCodes["LISTING_TOO_MANY_MEMBERS"] = 120001] = "LISTING_TOO_MANY_MEMBERS";
    DiscordAbortCodes[DiscordAbortCodes["LISTING_JOIN_BLOCKED"] = 120002] = "LISTING_JOIN_BLOCKED";
    DiscordAbortCodes[DiscordAbortCodes["RESOURCE_OVERLOADED"] = 130000] = "RESOURCE_OVERLOADED";
    DiscordAbortCodes[DiscordAbortCodes["INVALID_LOTTIE"] = 170001] = "INVALID_LOTTIE";
})(DiscordAbortCodes = exports.DiscordAbortCodes || (exports.DiscordAbortCodes = {}));
var DiscordHeaders;
(function (DiscordHeaders) {
    DiscordHeaders["AUDIT_LOG_REASON"] = "x-audit-log-reason";
    DiscordHeaders["DEBUG_OPTIONS"] = "x-debug-options";
    DiscordHeaders["FINGERPRINT"] = "x-fingerprint";
    DiscordHeaders["SUPER_PROPERTIES"] = "x-super-properties";
    DiscordHeaders["TRACK"] = "x-track";
})(DiscordHeaders = exports.DiscordHeaders || (exports.DiscordHeaders = {}));
var RatelimitHeaders;
(function (RatelimitHeaders) {
    RatelimitHeaders["BUCKET"] = "x-ratelimit-bucket";
    RatelimitHeaders["GLOBAL"] = "x-ratelimit-global";
    RatelimitHeaders["LIMIT"] = "x-ratelimit-limit";
    RatelimitHeaders["PRECISION"] = "x-ratelimit-precision";
    RatelimitHeaders["REMAINING"] = "x-ratelimit-remaining";
    RatelimitHeaders["RESET"] = "x-ratelimit-reset";
    RatelimitHeaders["RESET_AFTER"] = "x-ratelimit-reset-after";
    RatelimitHeaders["RETRY_AFTER"] = "retry-after";
})(RatelimitHeaders = exports.RatelimitHeaders || (exports.RatelimitHeaders = {}));
var RatelimitPrecisionTypes;
(function (RatelimitPrecisionTypes) {
    RatelimitPrecisionTypes["MILLISECOND"] = "millisecond";
    RatelimitPrecisionTypes["SECOND"] = "second";
})(RatelimitPrecisionTypes = exports.RatelimitPrecisionTypes || (exports.RatelimitPrecisionTypes = {}));
var RestEvents;
(function (RestEvents) {
    RestEvents["REQUEST"] = "request";
    RestEvents["RESPONSE"] = "response";
})(RestEvents = exports.RestEvents || (exports.RestEvents = {}));
exports.RATELIMIT_BUCKET_MAJOR_PARAMS = Object.freeze(['channelId', 'guildId', 'webhookId', 'webhookToken']);
exports.SPOILER_ATTACHMENT_PREFIX = 'SPOILER_';
// https://github.com/discordapp/discord-api-docs/issues/1092
// add 200 ms leeway incase our clock is wrong or the request takes too long
exports.MESSAGE_DELETE_RATELIMIT_CHECK = ((10) * 1000) - 200; // 10 seconds
exports.MESSAGE_DELETE_RATELIMIT_CHECK_OLDER = ((2 * 7 * 24 * 60 * 60) * 1000) - 200; // 2 weeks
